### ISSUE TITLE
Cc and AdminCc on multiple lines

### ISSUE THREAD

**Issue by larrys** [CZ-NIC/python-rt#10]
Cc and AdminCc will flow onto separate lines if there are enough entries. Requestors does as well, but does not have this problem, as there are some extra handling of this to account for this. Cc and AdminCc need the same bit of logic to handle multiple lines.

**Comment by inputvalidation** [comment]
I'm affected by this as well. The RT API responds with:

```
Requestors: user@domain.com

Cc: user-b@domain.com,
    user-c@domain.com, user-d@domain.com,
    user-e@domain.com

AdminCc:
```

The result of search() contains (I've shortened it a bit):

```
  "Requestors": [
    "user@domain.com"
  ],
  "Cc": [
    "user-b@domain.com",
    ""
  ],
```

A fix would be appreciated.
