### ISSUE TITLE
Issue with custom fields containing multiple lines

### ISSUE THREAD

**Issue by ap113** [CZ-NIC/python-rt#11]
It seems that there is an issue when you use a custom field that can contains text. If the multiple lines are entered separated by a carriage return, only the first line of the text is returned.

**Comment by wari** [comment]
@ap113 if your other lines are indented 4 spaces, would that work for your custom field?

**Comment by wagner-certat** [comment]
@ap113 can you show some example code?

**Comment by ap113** [comment]
@wagner-certat the code is quite simple, it uses only the search method (tracker.search(Queue=rtQueue, raw_query=query), query = "{'query': '(Queue=\'Inbox') AND (Status+=+"new"+OR+Status+=+"stalled"+OR+Status+=+"open")', 'format': 'l'}"), the problem as far as I can see is that the code splits by line, and it pairs the lines with the key (name of the custom field). The problem seems to be that the pairing is only made with the first line and the rest is not returned when the value of the custom field is "First line \n Second line".
From what I can see in the debugging is that the list in 'msgs' variable contains the all the lines from the custom fields but when the value contain a carriage return, the pairing is giving :
"CF.{name_of_the_field}: First line" and not "CF.{name_of_the_field}: First line \n Second line", so there is an item in the list with only the value "Second line'. 
So when 'items' variable is populated, only the line with "CF.{name_of_the_field}: First line" is appended.
I hope that it is clear.

**Comment by wagner-certat** [comment]
@ap113 Thanks, now I understand the issue

**Comment by etoddatkins** [comment]
The fix mentioned in #39 does not include a fix for get_ticket.

**Comment by jerash** [comment]
hello @etoddatkins , I had same problem and made a dity hack to make it work for my use case.  
Diff attached, but it would probably need better code for production, and should be tested with your environment.
hope it is usefull anyway.
[rt.txt](https://github.com/CZ-NIC/python-rt/files/5180486/rt.txt)

**Comment by petterreinholdtsen** [comment]
@jerash A unified diff (diff -u) would be easier to read.  Any chance you could attach it using that format?

**Comment by jerash** [comment]
@petterreinholdtsen you are correct, here is the diff with correct format
[rt.py.diff.txt](https://github.com/CZ-NIC/python-rt/files/5523389/rt.py.diff.txt)
