### ISSUE TITLE
Return numeric ticket id from tracker.search?

### ISSUE THREAD

**Issue by danmichaelo** [CZ-NIC/python-rt#24]
Hi! First thing that puzzled me with this library was that the ids returned from the search method is on the form "ticket/{numeric id}", so they cannot be passed directly to other methods like this:

```python

for ticket in tracker.search(...):
    tracker.get_attachments(ticket['id'])
```

Wouldn't it be nice if they could? What is the reason for including the "ticket/" prefix?

**Comment by e3rd** [comment]
Sorry, I am a maintainer but not a library user and I have no clue why that is happening. If you figure out if there is/isn't an advantage in this and create a PR, I may merge it.

**Comment by wagner-certat** [comment]
I also don't know why this is the case. It could also be an unwanted change in the past.

> Wouldn't it be nice if they could?

Definitely.

However, a breaking change triggers a new major version of this library. One could also add a new item with only the ID and add a deprecation warning for the 'id' item. And with the next major release change apply the breaking change and deprecate the other (added) item.
