### ISSUE TITLE
Please remove our RT demo instance from your test suite

### ISSUE THREAD

**Issue by elacour** [CZ-NIC/python-rt#28]
Our RT demo instance is publicly available, but it doesn't mean you can use it for software test suite without even having contacted us. Any user of this rt client that run a those tests create ticket on our instance....
I'm sorry, I closed access to /REST/1.0 on our server.

**Comment by wagner-certat** [comment]
PR #29 will disable them.

Do you know any other public RT instance we could use?

**Comment by petterreinholdtsen** [comment]
In addtiont to disabling the tests, is it not sensible to also remove the URL to the service?  After all, the owner of the service seem to not want you to announce its existence in this code base.

**Comment by e3rd** [comment]
@elacour I'm sorry for any inconveniences we did by using your instance in the tests.
