### ISSUE TITLE
Flexible certificate handling

### ISSUE THREAD

**Issue by e3rd** [CZ-NIC/python-rt#3]
Author: Andrew Hills
(migrated from gitlab)

Please consider the attached patch, which adds an `ssl_verify` option to allow communicating with servers using self-signed certificates. Per the requests documentation, it can be set to `True` for default behavior, `False` to avoid performing verification, or a path to a certificate for verification. It applies cleanly to rt-1.0.9.

[patch_rt-1.0.9-ssl-verify.patch](/uploads/8a76c2b4542d87e71b5937e09cd97ce9/patch_rt-1.0.9-ssl-verify.patch)

**Comment by ahills** [comment]
This was not fixed by #6, as far as I can tell.

**Comment by e3rd** [comment]
Hello, @sim0nx named the parameter not "ssl_verify" (as you requested in the patch) but "verify_cert", I don't know why.
But beside that the functionality seems the same as in your patch:

https://github.com/CZ-NIC/python-rt/commit/99947ef015816b73451c91b828b384b824c3011d

Do you need the name to be "ssl_verify"?

**Comment by ahills** [comment]
You're right; nevermind! The name doesn't matter at all, as long as the functionality is the same.
