### ISSUE TITLE
Support python 3?

### ISSUE THREAD

**Issue by petterreinholdtsen** [CZ-NIC/python-rt#31]
Hi.  When trying to use python-rt with Python 3, I end up with problems saving as json the content of the dict returned from get_attachment(), because only some of the values are binary and others are str.  It would be great if the library worked with Python 3 too.

**Comment by sim0nx** [comment]
Can you elaborate on your problems, what you are trying to do (sample code).
We are using it with PY3 and I am currently not aware of any issues, but am happy to cross check with specific code.

**Comment by petterreinholdtsen** [comment]
[Georges Toth]
> Can you elaborate on your problems, what you are trying to do (sample code).
> We are using it with PY3 and I am currently not aware of any issues,
> but am happy to cross check with specific code.

The code involved is available from 
<URL: https://gitlab.com/petterreinholdtsen/request-tracker-noark5extract >,
and the problem is with write(json.dumps(data)) where one of the values
in the dict is bytes, not string, possibly because it contain UTF-8
characters.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by sebix** [comment]
Can you please give an example so we can try to reproduce it? Only `write(json.dumps(data))` is definitely not enough.

**Comment by danmichaelo** [comment]
Seems to work fine with Python 3.6 afaics.

**Comment by sim0nx** [comment]
Starting with https://github.com/CZ-NIC/python-rt/commit/955941b49d836fcbe954dfee31b85b380db11aa4 this library is Python3 only. Has been long in production here and elsewhere with PY3 without any issues so I think this issue can be closed @e3rd .

**Comment by petterreinholdtsen** [comment]
[Georges Toth]
> Starting with
> https://github.com/CZ-NIC/python-rt/commit/955941b49d836fcbe954dfee31b85b380db11aa4
> this library is Python3 only. Has been long in production here and
> elsewhere with PY3 without any issues so I think this issue can be
> closed @e3rd .

I lack the spare time required to look into making a minimal examle
demonstrating the problem.  I suspect it has something to do with the
æøåÆØÅ characters commonly used in Norway and their representation in
UTF-8 and/or ISO-8859-1.  Hopefully it has gone away in later versions
of python-rt. :)

-- 
Happy hacking
Petter Reinholdtsen
