### ISSUE TITLE
Including python-rt in Debian?

### ISSUE THREAD

**Issue by petterreinholdtsen** [CZ-NIC/python-rt#32]
Hi

Are you interested in having python-rt included as an official package in Debian and derivatives like Ubuntu? I've created a request for a python-rt package in Debian (aka a WNPP request), and thought it best to check with you if this is something you welcome and would like to help make happen.

I am a Debian developer and can assist. It is a lot easier to do when the Debian maintainer and the upstream developers cooperate, so I find it best to ask up front if you are interested.

**Comment by petterreinholdtsen** [comment]
The WNPP request is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913211 .

**Comment by sebix** [comment]
Hi,

Yes, we'd be interested in this, thanks for your interest in making this happen. Do you need any support? AFAIK it is very easy in this case. Here I build several deb and rpm packages for this library: https://build.opensuse.org/package/show/home:sebix:intelmq/python3-rt

**Comment by petterreinholdtsen** [comment]
[Sebastian]
> Yes, we'd be interested in this, thanks for your interest in making
> this happen. Do you need any support? AFAIK it is very easy in this
> case. Here I build several deb and rpm packages for this library:
> https://build.opensuse.org/package/show/home:sebix:intelmq/python3-rt

It make me very glad to read this.  It make it a lot easier for
prospective package maintainers. :)

Due to me having little spare time and way to many packages to look
after in Debian already, my preferred approach would be for someone else
to maintain the package, and me taking the role of advisor and "package
sponsor" (ie the one uploading a package to Debian on behalf of others).

Would you be interested in taking the role of package maintainer?  The
process and requirements are well documented, <URL:
https://www.debian.org/doc/manuals/developers-reference/ > is a good
place to start.  My sponsoring preferences can be found on
<URL: http://www.hungry.com/~pere/debian-sponsoring.html >.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by sebix** [comment]
> Would you be interested in taking the role of package maintainer?

Yes. I will approach you when I (think I) am ready.

**Comment by b1rger** [comment]
`python-rt` is now in Debian unstable: https://tracker.debian.org/news/1188244/accepted-python-rt-201-1-source-all-into-unstable-unstable/
