### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by wagner-certat** [CZ-NIC/python-rt#42]
There are quite [some changes](https://github.com/CZ-NIC/python-rt/compare/v1.0.11...master) since the last 1.0.11 release including various bug fixes.

Can please someone (@e3rd ?) make a new release please?

**Comment by rixx** [comment]
For everybody who's not that familiar with pip: Until there has been a new release, you can install the current version with

```
pip install git+https://github.com/CZ-NIC/python-rt.git
```

You can append a "@commithash" for a specific commit.

**Comment by e3rd** [comment]
Finally released here and on (PyPi)[https://pypi.org/project/rt/1.0.12/], I've finally successfully setup PyPi keys for quicker uploading, sorry and thanks for the patience!
