### ISSUE TITLE
make html does not work correctly

### ISSUE THREAD

**Issue by Piuliss** [CZ-NIC/python-rt#44]
Hi  CZ-NIC,
thanks for your collaboration. I really like your library. 
For avoiding read the source, I am trying to generate the documentation. So, I did:
```
cd <PROJECT_PATH>/python-rt/doc
make html
```

It generates and html folder with several files in it, for instance `index.html`. When I open it, it is simple or basic html with no information regarding source code or any documentation, just basic information provided by sphinx
Sphinx version:
```
Name: Sphinx
Version: 1.8.5
```

**Comment by e3rd** [comment]
Thanks!  
Unfortunately, I'm a mere maintainer with no previous experience with Sphinx. Therefore since this is not critical and docstrings are clearly visible in the source file, I won't prioritize this issue. Have a nice day.

**Comment by e3rd** [comment]
This should be working now thanks to sim0nx, I've tested it locally.
