### ISSUE TITLE
UnicodeDecodeError in logging code for non-text attachments

### ISSUE THREAD

**Issue by wagner-certat** [CZ-NIC/python-rt#50]
While this is well-intentioned, it turns out to be not working well:

https://github.com/CZ-NIC/python-rt/blob/2cfe207ad6e4de323867862973d81291e13be1a6/rt/rt.py#L197-L198

If the response is not text, but for example archive, decoding fails (irrespective of the logging level) and leads to this:

```
...
    attachment = RT.get_attachment_content(ticket_id, att_id)
  File "/usr/local/lib/python3.7/dist-packages/rt/rt.py", line 1029, in get_attachment_content
    text_response=False)
  File "/usr/local/lib/python3.7/dist-packages/rt/rt.py", line 198, in __request
    self.logger.debug(response.content.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 29: invalid continuation byte
```

**Comment by sim0nx** [comment]
I have done a quick PR in #51 to address this issue.

**Comment by e3rd** [comment]
Amazing!
