### ISSUE TITLE
How to filter tickets by date?

### ISSUE THREAD

**Issue by jose-caballero** [CZ-NIC/python-rt#58]
Hello,

I know this is not really an "issue", but a question. However, I am not aware of any mailing list to forum to ask questions, so I am asking this via issue. My apologies for it. 

How can I use rt to get the list of tickets that were Created before date1 and after date2, for example?
I have tried something like this 

tracker.search(Queue="myqueue", raw_query='Created > 1601506800') using seconds since epoch,but no luck.

Also tried with str(datetime.datetime.strptime(<the date here>), but no luck either.
Do you have an example of using dates in queries?

Thanks a lot in advance.
Cheers,
Jose

**Comment by craigkai** [comment]
Did you try that search in the RT web UI as the user who you are logging in as through Python? That query seems to return tickets for me and so does using relative date values ( Although it looks like I need to include a 'Queue' value for the search to work )

```python3
 tracker.search(Queue="general", raw_query='Created > "2 days ago"')
```

**Comment by jose-caballero** [comment]
Hi @craigkai

That gave me the solution. This works: 

`tracker.search(Queue="myqueue", raw_query='Created > "2020-10-01"')
`   

Thanks a lot!!

BTW, what is the correct way to ask questions? I can imagine opening _issues_ is not the most recommendable approach... Is there a mailing list or a more proper forum for questions? 

Cheers,
Jose

**Comment by craigkai** [comment]
Yes there is a forum:

https://forum.bestpractical.com

**Comment by wagner-certat** [comment]
> BTW, what is the correct way to ask questions? I can imagine opening issues is not the most recommendable approach... Is there a mailing list or a more proper forum for questions?

Adding to what @craigkai said, for python-rt there is no separate forum or mailing list, as there are not enough questions to justify the effort. Opening issues is fine :)
