### ISSUE TITLE
Where do I need to copy the server certificate?

### ISSUE THREAD

**Issue by jose-caballero** [CZ-NIC/python-rt#59]
Hi, 

I am on Mac laptop, Catalina. 
I haven't figured out yet where exactly should I copy the server root certificate to avoid these WARNING messages:

$ uname
Darwin

$ python -V
Python 2.7.16

import rt 
tracker = rt.Rt('https://myserver/REST/1.0/', 'me', 'mypassword', verify_cert=False)
tracker.login()
/Library/Python/2.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'helpdesk.gridpp.rl.ac.uk'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

Any suggestion for a path for the root certificate? Or any other mechanism to prevent those WARNINGs from happening on every action?

Thanks a lot in advance. 
Cheers,
Jose

**Comment by wagner-certat** [comment]
rt is using the requests library, maybe this helps: https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification

Btw, I recommend to switch to Python 3
