### ISSUE TITLE
Update Links on pypi

### ISSUE THREAD

**Issue by vinzBad** [CZ-NIC/python-rt#7]
https://pypi.python.org/pypi/rt still points to the old gitlab site.

**Comment by e3rd** [comment]
Don't you know please how could I gain the access to the PyPi project?
I let live the old gitlab site in order the people can get here from there.

**Comment by wagner-certat** [comment]
@e3rd The owner of the package on pypi is "machalekj.mojeid.cz"

**Comment by sim0nx** [comment]
Any news on this?

**Comment by e3rd** [comment]
Thanks for reminding me :)

**Comment by vinzBad** [comment]
Bug tracker link still points to  https://gitlab.labs.nic.cz/labs/python-rt/issues

**Comment by e3rd** [comment]
I've been trying few hours to set it via setup.py, METADATA in wheel, and by web interface but without luck.
It seems to be wider problem, see the unanswered question:

https://stackoverflow.com/questions/46617605/how-do-you-set-the-bugtrack-url-field-in-pypi-metadata

**Comment by sim0nx** [comment]
Looking at the new pypi page, this issue seems to be resolved.

**Comment by e3rd** [comment]
Great, thanks for your vigilance. I really prefer the issues that resolve itself.
